#!/usr/bin/env bash
# Test suite for guard.py. Run: bash scripts/hooks/test-guard.sh   (exit 1 on any mismatch)
cd "$(dirname "$0")/../.." || exit 1
AD=$PWD; W=$AD/lanes/docs/docs; fail=0
# These cases are written against a configured workspace: a lane with a repo in it, a mirror,
# and an attached reference. On a fresh install none of that exists yet, and "no fixtures" is not a
# failure — say so and stop, so `lane doctor` stays the check that always works.
if [ ! -d "$W" ] || [ ! -d "$AD/repos/$(basename "$W")" ]; then
  echo "Skipped: this suite needs a configured workspace (a lane, its repo, and a mirror)."
  echo "The always-available check is:  lane doctor"
  exit 0
fi
# A second, live lane to test reach-in against. Chosen at run time, because hardcoding
# one meant the suite started failing the day that lane was closed.
OTHER=$(for d in "$AD"/lanes/*/; do id=$(basename "$d"); [ "$id" = docs ] && continue;
  for r in "$d"*/; do [ -e "$r/.git" ] && { echo "${id}/$(basename "$r")"; break 2; }; done; done)
[ -n "$OTHER" ] || { echo "no second lane on disk - cannot test reach-in"; exit 1; }
j(){ python3 -c 'import json,sys;print(json.dumps(sys.argv[1]))' "$1"; }
run(){ printf '%s' "$1" | python3 scripts/hooks/guard.py 2>/dev/null | grep -o '"permissionDecision": "[a-z]*"' | cut -d'"' -f4; }
expect(){ # expect <deny|allow|pass> <label> <json>
  got=$(run "$3"); got=${got:-pass}
  if [ "$got" = "$1" ]; then printf "  ok    %-6s %s\n" "$got" "$2"; else printf "  FAIL  want %-5s got %-5s %s\n" "$1" "$got" "$2"; fail=1; fi
}
bash_case(){ expect "$1" "bash: $2" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$W\",\"tool_input\":{\"command\":$(j "$2")}}"; }
file_case(){ expect "$1" "$2 $3" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"$2\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"$3\"}}"; }

echo "== secrets: files"
file_case deny  Read "$W/.env"
file_case deny  Read "$AD/lanes/ABC-123-example/worker/.env"
file_case deny  Edit "$W/server/.env"
file_case deny  Read "$W/certs/server.key"
file_case allow Read "$W/.env.example"
file_case allow Read "$W/app.py"
echo "== secrets: bash must deny"
for c in "cp ../../repos/docs/.env .env" "ln -s ../../repos/docs/.env .env" "cat .env" "grep DATABASE_URL .env" "source .env && npm start" "set -a; . ./.env; set +a" \
         "python3 -c \"print(open('.env').read())\"" "sed -n 1,5p server/.env" "cat < .env" \
         "head ../../repos/docs/.env" "cat key.pem" "cat credentials.json" "echo \"\$(cat .env)\"" "printf '%s' \$(< .env)"; do bash_case deny "$c"; done
echo "== secrets: bash must pass"
for c in "ls -la .env" "lane-env-keys .env" "test -f .env && echo yes" "docker compose up" "npm run dev" "cat .env.example" "git status" "wc -c .env" \
         "python3 app.py" "uvicorn app.main:app" "echo done"; do bash_case pass "$c"; done
echo "== mirrors and lanes"
file_case deny  Edit "$AD/repos/docs/app.py"
file_case deny  Edit "$AD/lanes/$OTHER/x.ts"
file_case allow Edit "$W/app.py"
bash_case deny "git -C $AD/repos/docs checkout -b x"
bash_case pass "git -C $AD/repos/docs fetch origin"
bash_case deny "git stash"
bash_case pass "git stash push -u -m tag"
bash_case deny "git push --force origin docs:main"
bash_case deny "rm -rf $AD/lanes/docs"
expect pass "lane-start from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"scripts/lane-start foo docs\"}}"
echo "== old checkouts are frozen"
OUTSIDE=$(dirname "$AD")            # the folder lane sits in — outside it by construction
OLDFE=$OUTSIDE/some-other-checkout
CLONES=$OUTSIDE/clones/some-repo
file_case deny Read "$OLDFE/package.json"
expect deny "Grep in clones/" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Grep\",\"cwd\":\"$W\",\"tool_input\":{\"pattern\":\"x\",\"path\":\"$CLONES\"}}"
bash_case deny "git -C $OLDFE log --oneline -3"
bash_case deny "ls ~/.cursor/worktrees/web"
bash_case pass "scripts/status-all"
echo "== no new worktrees from inside a lane"
expect deny "EnterWorktree from worktree" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$W\",\"tool_input\":{\"name\":\"x/docs\"}}"
expect pass "EnterWorktree name=<id> from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"name\":\"docs\"}}"
expect deny "EnterWorktree name=<id>/<repo>" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"name\":\"docs/docs\"}}"
expect deny "EnterWorktree with a path" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"path\":\"$AD/lanes/docs/docs\"}}"
expect deny "EnterWorktree with nothing" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{}}"
bash_case deny "git worktree add ../x docs"
bash_case deny "lane-start other docs"
bash_case deny "lane-add other-ws api"
bash_case pass "lane-add docs api"
bash_case pass "lane-brief docs"
echo "== cert/key tokens: only standalone paths count"
bash_case pass "node -e 'const k=e.key; console.log([e.key])'"
bash_case pass "python3 -c 'print(d.pem)'"
bash_case deny "cat server.key"
bash_case deny "cat ./certs/server.key"
bash_case deny "openssl x509 -in cert.pem -text"
echo "== memory / control-plane gate"
file_case deny  Write "$AD/memory/docs/x.md"
file_case deny  Write "$AD/memory/new-note.md"
file_case deny  Edit  "$AD/knowledge/preferences.md"
file_case deny  Write "$AD/CLAUDE.md"
file_case deny  Write "$AD/scripts/lane-start"
file_case deny  Write "$AD/registry/repos.yaml"
file_case deny  Write "$AD/registry/lanes/ABC-123-example.md"
expect pass "own lane spec" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Write\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"$AD/registry/lanes/docs.md\"}}"
bash_case deny "echo x >> $AD/memory/MEMORY.md"
bash_case deny "cp /tmp/a.md $AD/memory/docs/a.md"
bash_case pass "lane-memory file foo cross"
bash_case pass "cat $AD/memory/MEMORY.md"
expect pass "control plane from the root session" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Write\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/CLAUDE.md\"}}"
bash_case pass "lane-memory rm zz-move"
bash_case pass "bin/lane-memory move zz cross && grep -c zz $AD/memory/MEMORY.md"
bash_case deny "cd /tmp && rm $AD/memory/docs/x.md"
bash_case pass "grep -rn foo $AD/memory/"
echo "== memory: edit an existing one from the dispatcher, never create"
expect pass "edit existing memory at root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/memory/commit-discipline.md\"}}"
expect pass "edit preferences at root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/knowledge/preferences.md\"}}"
expect deny "create a NEW memory at root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Write\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/memory/brand-new-thing.md\"}}"
expect deny "edit existing memory from a worktree" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"$AD/memory/commit-discipline.md\"}}"
echo "== cd is not a second door"
expect deny "cd into a lane from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"cd lanes/docs/docs\"}}"
expect deny "cd into a lane root from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"cd $AD/lanes/docs && ls\"}}"
expect deny "cd into a mirror" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"cd repos/docs\"}}"
expect deny "cd into another lane from a worktree" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$W\",\"tool_input\":{\"command\":\"cd ../../$OTHER\"}}"
bash_case pass "cd $AD/lanes/docs/docs/app && ls"
bash_case pass "git -C $AD/repos/docs log --oneline -1"
expect pass "cd inside lane root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"cd docs && ls\"}}"
echo "== confined to lane"
file_case deny  Read "$HOME/Desktop/your-org/legacy-app/package.json"
file_case deny  Read "$HOME/.claude/settings.json"
file_case allow Read "$W/app.py"
expect pass "read the scratchpad" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Read\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"${TMPDIR:-/tmp}/scratch/x.txt\"}}"
expect pass "read a system path" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Read\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"/usr/share/dict/words\"}}"
file_case deny  Read "$HOME/Desktop/your-org/docs/README.md"
file_case allow Read "$AD/lanes/docs/refs/client-docs/README.md"
echo "== git: the remote and default branches are not Claude's to change"
bash_case deny "git remote set-url origin git@github.com:x/y.git"
bash_case deny "git remote add upstream https://example.com/x.git"
bash_case deny "git push origin docs:main"
bash_case deny "git push origin main"
bash_case pass "ALLOW_DEFAULT_BRANCH_PUSH=1 git push origin docs:main"
bash_case pass "git push origin docs"
bash_case deny "git branch -f main abc123"
bash_case deny "git update-ref refs/heads/main abc123"
bash_case pass "git remote -v"
echo "== our own lane-* commands are exempt from the path rules"
bash_case pass "lane-ref docs rm client-docs"
bash_case pass "lane-ref docs list"
bash_case pass "lane-memory rm foo"
bash_case pass "lane-brief docs && lane-status"
expect pass "lane-ref add an outside path" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"lane-ref docs add $HOME/Desktop/your-org/legacy-app widget\"}}"
echo "== writing to a read-only reference is still refused"
bash_case deny "sed -i '' s/a/b/ $AD/lanes/docs/refs/client-docs/README.md"
bash_case deny "rm $AD/lanes/docs/refs/client-docs/x.txt"
bash_case deny "lane-status && rm $AD/lanes/docs/refs/client-docs/x.txt"
bash_case pass "cat $AD/lanes/docs/refs/client-docs/README.md"
echo "== a session inside a lane stays inside it"
bash_case deny "cd $AD && lane-status"
bash_case deny "cd /tmp && ls"
bash_case deny "cd ~"
expect deny "cd to a sibling repo" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD/lanes/ABC-124-example/web\",\"tool_input\":{\"command\":\"cd ../api && git status\"}}"
bash_case pass "cd refs && ls"
bash_case pass "lane-status"
bash_case pass "git -C ../api status"
echo "== the dispatcher cannot reach into a lane"
expect deny "edit a lane file from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/lanes/docs/docs/app.py\"}}"
expect deny "read a lane file from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Read\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/lanes/docs/docs/app.py\"}}"
expect deny "write a lane file from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Write\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/lanes/docs/docs/new.py\"}}"
expect deny "bash rm into a lane from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"rm $AD/lanes/docs/docs/x.txt\"}}"
expect deny "bash sed -i into a lane from root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"sed -i '' s/a/b/ lanes/docs/docs/app.py\"}}"
expect pass "lane-brief reads it for you" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD\",\"tool_input\":{\"command\":\"lane-brief docs\"}}"
expect pass "the registry file stays editable" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$AD\",\"tool_input\":{\"file_path\":\"$AD/registry/lanes/docs.md\"}}"
expect allow "inside the lane it is fine" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"cwd\":\"$W\",\"tool_input\":{\"file_path\":\"$W/app.py\"}}"
echo "== Bash cannot do what the file tools refuse"
bash_case deny "rm $AD/lanes/$OTHER/x.txt"
bash_case deny "sed -i '' s/a/b/ $AD/lanes/$OTHER/app.ts"
bash_case deny "cat $AD/lanes/$OTHER/app.ts"
bash_case deny "echo x >> $AD/lanes/$OTHER/app.ts"
bash_case deny "git -C $AD/lanes/$OTHER commit -am x"
bash_case deny "rm $AD/repos/docs/README.md"
bash_case deny "sed -i '' s/a/b/ $AD/repos/docs/README.md"
bash_case deny "echo x >> $AD/repos/docs/README.md"
bash_case pass "cat $AD/repos/docs/README.md"
bash_case pass "git -C $AD/repos/docs log --oneline -1"
bash_case pass "git -C ../web status"
bash_case pass "cp $AD/repos/docs/.env.example $W/.env.example"
bash_case deny "cp $W/x.txt $AD/repos/docs/x.txt"
bash_case deny "git -C $AD/repos/docs commit -am x"
bash_case pass "git -C $AD/repos/docs fetch origin"
echo "== choosing the repo to land in"
expect deny "name=<id>/<repo> is not a thing" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"name\":\"docs/docs\"}}"
expect deny "name=<id>/<repo> unknown repo" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"name\":\"docs/nope\"}}"
expect deny "name=<unknown>/<repo>" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD\",\"tool_input\":{\"name\":\"no-such-ws/docs\"}}"
echo "== lane-run / lane-gh: a shortcut, not a bypass"
bash_case pass "lane-gh api pr create --fill"
bash_case pass "lane-run api mvn -q -DskipTests package"
bash_case deny "lane-gh api repo delete your-org/api --yes"
bash_case deny "lane-gh api api -X DELETE repos/your-org/api/branches/main/protection"
bash_case deny "lane-run api git push origin main"
bash_case deny "lane-run api git remote set-url origin git@x:y.git"
bash_case deny "gh repo delete your-org/api --yes"
bash_case deny "gh api -X PATCH repos/x/y"
bash_case pass "gh pr list -R your-org/api"
echo "== the control plane cannot be rewritten from a shell (self-disarm)"
# A shell redirect reached files the file tools refuse, including a lane's own
# settings.local.json — which switches its hooks off entirely.
bash_case deny  "echo x > $AD/scripts/hooks/guard.py"
bash_case deny  "rm -f $AD/scripts/hooks/guard.py"
bash_case deny  "mv $AD/scripts/hooks/guard.py /tmp/g"
bash_case deny  "cp /tmp/x $AD/scripts/hooks/guard.py"
bash_case deny  "ln -sf /etc/passwd $AD/scripts/hooks/guard.py"
bash_case deny  "sed -i '' s/deny/allow/g $AD/scripts/hooks/guard.py"
bash_case deny  "echo x > ../../../scripts/hooks/guard.py"
bash_case deny  "echo x > $AD/CLAUDE.md"
bash_case deny  "echo x > $AD/docs/rules.md"
bash_case deny  "echo x > $AD/registry/repos.yaml"
bash_case deny  "echo '{}' > $AD/.claude/settings.json"
bash_case deny  "echo '{}' > $W/.claude/settings.local.json"
bash_case deny  "echo x > $AD/registry/lanes/$(basename "$OTHER" | cut -d/ -f1).md"
# ordinary work must be unaffected
bash_case pass  "echo x >> $W/app.py"
bash_case pass  "echo x > /tmp/scratch.txt"
bash_case pass  "cat $AD/docs/rules.md"

echo "== the session stays at the lane root"
expect deny "cd into a repo from the root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD/lanes/docs\",\"tool_input\":{\"command\":\"cd docs && ls\"}}"
expect pass "cd back to the lane root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$W\",\"tool_input\":{\"command\":\"cd .. && ls\"}}"
expect pass "cd within the repo you are pinned in" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$W\",\"tool_input\":{\"command\":\"cd app && ls\"}}"
expect pass "lane-run instead of cd" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Bash\",\"cwd\":\"$AD/lanes/docs\",\"tool_input\":{\"command\":\"lane-run docs git status\"}}"
echo "== re-pinning: aiming at your OWN lane says how, not 'do not create another'"
expect deny "EnterWorktree path=own lane root" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD/lanes/docs/docs\",\"tool_input\":{\"path\":\"$AD/lanes/docs\"}}"
expect deny "EnterWorktree name=own lane" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD/lanes/docs/docs\",\"tool_input\":{\"name\":\"docs\"}}"
expect deny "EnterWorktree name=another lane" "{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"EnterWorktree\",\"cwd\":\"$AD/lanes/docs/docs\",\"tool_input\":{\"name\":\"ABC-124-example\"}}"
[ $fail -eq 0 ] && echo "ALL PASS" || { echo "FAILURES"; exit 1; }
